<?php
require "config.php";
/*
SELECT p.id, p.post_title, (

SELECT p2.guid
FROM wp_posts AS p2
WHERE pm.meta_value = p2.ID
LIMIT 1
) AS featured_image
FROM wp_posts AS p
INNER JOIN wp_postmeta AS pm ON p.ID = pm.post_id
WHERE pm.meta_key =  '_thumbnail_id'
*/

/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `jardinss_wrd1`
//

// `jardinss_wrd1`.`wp_posts`
$wp_posts = array(
  array('id' => '1037','post_title' => 'Mealy Cup Sage (Salvia Farinacea)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP9244.jpg'),
  array('id' => '2386','post_title' => 'Just Coleus!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_63521.jpg'),
  array('id' => '2401','post_title' => 'Impatiens','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_6573.jpg'),
  array('id' => '694','post_title' => 'A Colorful Flower  Bed','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/08/IMGP8189.jpg'),
  array('id' => '373','post_title' => 'A visit to the Jardins du Monastere de Cimiez, France','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/08/IMGP8207.jpg'),
  array('id' => '704','post_title' => 'Flower Bed 2','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/08/IMGP8141.jpg'),
  array('id' => '625','post_title' => 'How to remove grass and weeds before planting?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/07/P1020261.jpg'),
  array('id' => '284','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/07/early-sun.jpg'),
  array('id' => '14619','post_title' => 'A Grand Entry - Pedersen Associates ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Pederson-Associates2.jpg'),
  array('id' => '14594','post_title' => 'A Welcoming path - Goodman Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Goodman-Landscape3.jpg'),
  array('id' => '14604','post_title' => 'A Lavender Path - Verdance Fine Garden Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Verdance-Fine-Garden.jpg'),
  array('id' => '14609','post_title' => 'A Serene Garden Retreat - Verdance Fine Garden Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Verdance-Fine-Garden3.jpg'),
  array('id' => '248','post_title' => 'Welcome at Ephrussi de Rothschild, France','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP84991.jpg'),
  array('id' => '945','post_title' => 'A Glowing Flower Bed','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8260-bis.jpg'),
  array('id' => '1390','post_title' => 'Coleus (Solenostemon)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/diptwinecol.jpg'),
  array('id' => '1168','post_title' => 'French Marigold (Tagetes Patula)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_69552.jpg'),
  array('id' => '1195','post_title' => 'Begonia Stara (Begonia Semperflorens)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8267.jpg'),
  array('id' => '1235','post_title' => 'Purple Amaranth (Amaranthus Cruentus Oeschsberg)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82581.jpg'),
  array('id' => '1246','post_title' => 'African Marigold (Tagetes Erecta)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82571.jpg'),
  array('id' => '1258','post_title' => 'Golden Marguerite (Anthemis Tinctoria)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82561.jpg'),
  array('id' => '1266','post_title' => 'Black-Eyed Susan \'Autumn Colors\' (Rudbeckia Hirta)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8262-bis.jpg'),
  array('id' => '1276','post_title' => 'Tickseed (Coreopsis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_2748.jpg'),
  array('id' => '1299','post_title' => 'A Colorful Flower Bed','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8189.jpg'),
  array('id' => '1309','post_title' => 'Bloodleaf Wallisii (Iresine) ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8190_2.jpg'),
  array('id' => '1349','post_title' => 'Bloodleaf Lindenii (Iresine)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8187-Version-3.jpg'),
  array('id' => '1357','post_title' => 'Cannas','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/31114-Canna.jpg'),
  array('id' => '1368','post_title' => 'Begonia ‘Party Red’ (Begonia Semperflorens)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8190.jpg'),
  array('id' => '1383','post_title' => 'Nasturtium (Tropaeolum Majus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP9561.jpg'),
  array('id' => '1401','post_title' => 'New Guinea Impatiens','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_6602.jpg'),
  array('id' => '1410','post_title' => 'Purple-leaved Basil (Ocimum Basilicum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP9563-2.jpg'),
  array('id' => '1416','post_title' => 'Signet Marigold \'Signata\' (Tagetes Signata)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8189-Version-3.jpg'),
  array('id' => '1425','post_title' => 'Scarlet Sage (Salvia Splendens)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_81771.jpg'),
  array('id' => '1437','post_title' => 'Black-Eyed Susan \'Marmalade\' (Rudbeckia Hirta)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8193.jpg'),
  array('id' => '1446','post_title' => 'Zinnia (Zinnia Elegans)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_3250.jpg'),
  array('id' => '1459','post_title' => 'Bloodleaf Carminata (Iresine)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8175.jpg'),
  array('id' => '1479','post_title' => 'Klondyke Cosmos (Cosmos Sulphureus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_3368.jpg'),
  array('id' => '1487','post_title' => 'Black-Eyed Susan \'Goldilocks\' (Rudbeckia Hirta)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8215.jpg'),
  array('id' => '1501','post_title' => 'Purpletop Verbena (Verbena Bonariensis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_2915.jpg'),
  array('id' => '1508','post_title' => 'A Bright Airy Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82151.jpg'),
  array('id' => '1521','post_title' => 'Hummingbird Plant (Jacobinia or Justicia or Dicliptera Suberecta)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8221.jpg'),
  array('id' => '1531','post_title' => 'African Daisy or Cape Marigold (Dimorphotheca)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82191.jpg'),
  array('id' => '1545','post_title' => 'Mexican Daisy or Latin American Fleabane or Santa Barbara Daisy (Erigeron Karvinskianus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP7797.jpg'),
  array('id' => '1551','post_title' => 'A Lively Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8220.jpg'),
  array('id' => '10186','post_title' => 'Menton & Burgundy','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/DSC_9585.jpg'),
  array('id' => '1564','post_title' => 'Wax Begonia (Begonia Semperflorens)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82673.jpg'),
  array('id' => '1571','post_title' => 'French Marigold or Dwarf Marigold (Tagetes Patula)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8303.jpg'),
  array('id' => '1581','post_title' => 'Firecracker Plant, Coral Plant or Fountain Plant (Russelia Equisetiformis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8352.jpg'),
  array('id' => '1598','post_title' => 'An Eye Catching Staircase','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP83541.jpg'),
  array('id' => '1616','post_title' => 'An Eye Catching Wall','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8070.jpg'),
  array('id' => '1631','post_title' => 'A Tender Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP84541.jpg'),
  array('id' => '1656','post_title' => 'A Mediterranean Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_5903.jpg'),
  array('id' => '1662','post_title' => 'An Elegant Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP8489.jpg'),
  array('id' => '1678','post_title' => 'A Striking Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/DSC_5915.jpg'),
  array('id' => '1667','post_title' => 'Angel\'s Trumpets (Brugmansia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP80261.jpg'),
  array('id' => '244','post_title' => 'Private Tour in Handbury Botanical Gardens','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP8057.jpg'),
  array('id' => '1836','post_title' => 'Shrimp Plant (Justicia Brandegeana)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP8471.jpg'),
  array('id' => '1854','post_title' => 'A Welcoming Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP7972.jpg'),
  array('id' => '1871','post_title' => 'A Jardin Japonais in Monaco','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_60361.jpg'),
  array('id' => '1976','post_title' => 'A Visit to the Rockfellers\' Beloved Kykuit','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP9743.jpg'),
  array('id' => '2097','post_title' => 'A Botanical Garden on Lake Maggiore','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_62771.jpg'),
  array('id' => '2158','post_title' => 'The impressive Isola Madre','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_6447.jpg'),
  array('id' => '2215','post_title' => 'A Pyramid in Lake Maggiore ?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_6526.jpg'),
  array('id' => '2445','post_title' => 'A Classy Entrance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_65721.jpg'),
  array('id' => '2466','post_title' => 'Box Plants (Buxus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_6492.jpg'),
  array('id' => '2536','post_title' => 'Taming the Boxwood','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_64802.jpg'),
  array('id' => '2610','post_title' => 'Hosta \'Patriot\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/G740-0901020.jpg'),
  array('id' => '2561','post_title' => 'Hydrangeas','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP9829.jpg'),
  array('id' => '2622','post_title' => 'An Elegant Shady Corner','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP86542.jpg'),
  array('id' => '2653','post_title' => 'Palm-Leaf Begonia (Begonia Luxurians)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP8886.jpg'),
  array('id' => '2670','post_title' => 'Cranesbill \'Rozanne\' (Geranium)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP9533.jpg'),
  array('id' => '2679','post_title' => 'Impatiens Fusion \'Glow\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP8872.jpg'),
  array('id' => '2690','post_title' => 'Henry\'s Lily (Lilium Henryi)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP9957.jpg'),
  array('id' => '2719','post_title' => 'A Glowing Bed in Part Shade','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP9492.jpg'),
  array('id' => '2743','post_title' => 'Coneflowers (Echinacea)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/Echinacea_Aloha_1b.jpg'),
  array('id' => '2763','post_title' => 'Globe Thistle (Echinops Ritro)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP0036.jpg'),
  array('id' => '2776','post_title' => 'Garden Phlox (Phlox Paniculata)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP0219.jpg'),
  array('id' => '2821','post_title' => 'Balls and Cones !','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP97931.jpg'),
  array('id' => '2993','post_title' => 'Dahlias','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_6186.jpg'),
  array('id' => '3049','post_title' => 'Floss Flower (Ageratum Houstonianum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/DSC_6282.jpg'),
  array('id' => '3065','post_title' => 'Orange coneflower (Echinacea)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP8866.jpg'),
  array('id' => '3124','post_title' => 'Russian Sage (Perovskia Atriplicifolia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/Russian-Sage.jpg'),
  array('id' => '3142','post_title' => 'A Stunning Bed','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/IMGP9616-1.jpg'),
  array('id' => '3155','post_title' => 'Lobularia \'Snow Princess\' (Alyssum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/snow_princess_macro.jpg'),
  array('id' => '3172','post_title' => 'Sage \'Phyllis Fancy\' (Salvia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/DSC_6815.jpg'),
  array('id' => '3186','post_title' => 'Showy Stonecrop (Sedum Spectabile)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/66316.jpg'),
  array('id' => '3203','post_title' => 'Soft Autumn Colors','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/DSC_6822.jpg'),
  array('id' => '980','post_title' => 'A Joyful Summer Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/IMGP82691.jpg'),
  array('id' => '3394','post_title' => 'A White and Blue Garden - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/DSCN03371.jpg'),
  array('id' => '3445','post_title' => 'A Romantic Pond - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/DSCN0109.jpg'),
  array('id' => '3422','post_title' => 'A Hot Colored Garden - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/DSCN02141.jpg'),
  array('id' => '3664','post_title' => 'Jacqueline Van der Kloet\'s Tea garden / missing plant pictures','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/overzicht-april-2009-2.jpg'),
  array('id' => '3380','post_title' => 'Jacqueline Van der Kloet, Weesp Holland','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/persreis-2010-53.jpg'),
  array('id' => '3267','post_title' => 'Andrew Grossman, Massachusetts, USA','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/Shop-Front-end.jpg'),
  array('id' => '3803','post_title' => 'Tulip Types','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90128-Tulipa-Purissima.jpg'),
  array('id' => '3885','post_title' => 'Which Bulbs For Which Seasons ?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/206991-Tulipa-Willem-van-Oranje.jpg'),
  array('id' => '3974','post_title' => 'A Few Tips Before Buying Bulbs','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/Tulipa.jpg'),
  array('id' => '4016','post_title' => 'How To Plant Bulbs?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/207480-Tulipa1.jpg'),
  array('id' => '4081','post_title' => 'What Is a Bulb ?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/27554-Flowerbulbs.jpg'),
  array('id' => '3766','post_title' => 'Designing With Bulbs','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/11510-Lilium-Horizon-®.jpg'),
  array('id' => '4227','post_title' => 'A Soft Creamy Bed','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90076-Tulipa.jpg'),
  array('id' => '4338','post_title' => 'A Gorgeous Spring Display','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90090-Tulipa.jpg'),
  array('id' => '4364','post_title' => 'A Fresh Spring Mix - missing tulip name','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90082-Springflowering-Bulbs.jpg'),
  array('id' => '4385','post_title' => 'Spring Celebration','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/205620.jpg'),
  array('id' => '4403','post_title' => 'A Beautiful Lawn','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/206382-Anemone-blanda-White-Splendour1.jpg'),
  array('id' => '4442','post_title' => 'Pastel Colors - Jacqueline van der Kloet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90128.jpg'),
  array('id' => '4458','post_title' => 'A Blue River','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90057-Narcissus-Sailboat.jpg'),
  array('id' => '4469','post_title' => 'Festive Harmony','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/203020.jpg'),
  array('id' => '4486','post_title' => 'Pink Harmony','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/90426.jpg'),
  array('id' => '4501','post_title' => 'Festive Colors','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/206997-Tulipa-Willem-van-Oranje.jpg'),
  array('id' => '4509','post_title' => 'A Soft Summer Mix ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/205867-Summerflowering-Bulbs1.jpg'),
  array('id' => '4530','post_title' => 'Peach Delight','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/11499.jpg'),
  array('id' => '4546','post_title' => 'An Elegant Parterre - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/Gocester-RI-garden-6.10c.jpg'),
  array('id' => '4561','post_title' => 'A Simply Elegant Entry - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/Sharon-MA-walkway-1.jpg'),
  array('id' => '4568','post_title' => 'A Peaceful Rock Garden - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/Gocester-RI-garden-6.10e1.jpg'),
  array('id' => '4572','post_title' => 'A Californian Entrance - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/california.jpg'),
  array('id' => '3433','post_title' => 'A Cottage Garden in Seekonk - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/DSCN0239.jpg'),
  array('id' => '4603','post_title' => 'An Impressionist Border - Andrew Grossman','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/berkshires.jpg'),
  array('id' => '4634','post_title' => 'A Bridal Spring Mix - Jacqueline van der Kloet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/Bruidslaantje-2006-4-bis.jpg'),
  array('id' => '4680','post_title' => 'Orange Harmony - Jacqueline van der Kloet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/achter-april-3.jpg'),
  array('id' => '4698','post_title' => 'A Glorious Spring Bed - Jacqueline van der Kloet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44682.jpg'),
  array('id' => '4724','post_title' => 'A Purple River - Jacqueline van der Kloet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/voor-mei-8.jpg'),
  array('id' => '4756','post_title' => 'Hardiness Zones','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/Hardiness.jpg'),
  array('id' => '4825','post_title' => 'Sun or Light Needs: Definitions','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/15548-Tulipa.jpg'),
  array('id' => '4854','post_title' => 'Enough Light In My Garden?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/10822-Tulipa-Peach-Blossom.jpg'),
  array('id' => '618','post_title' => 'How To Enrich My Garden Soil With Organic Matter?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/07/17551-Springflowering-Bulbs1.jpg'),
  array('id' => '4887','post_title' => 'How To Make Organic Matter?','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/17551-Springflowering-Bulbs.jpg'),
  array('id' => '608','post_title' => 'Has my soil the right pH and level of nutrients ?   ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/07/207456-Narcissus.jpg'),
  array('id' => '4939','post_title' => 'Daffodil Types','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3326-Narcissus-Passionale.jpg'),
  array('id' => '4953','post_title' => 'Dutch Hyacinth Types','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/202645-Hyacinthus-Pink-Festival.jpg'),
  array('id' => '5035','post_title' => 'Grape Hyacinth (Muscari Armeniacum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/45053-Muscari-armeniacum.jpg'),
  array('id' => '22746','post_title' => 'A Simple & Charming Combo','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/40204.jpg'),
  array('id' => '5083','post_title' => 'Sage \'Mystic Spires\' Blue (Salvia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/DSC_6867.jpg'),
  array('id' => '5111','post_title' => 'Yarrow (Achillea)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/9270103.jpg'),
  array('id' => '5125','post_title' => 'Hairy Loosestrife (Lysimachia Ciliata)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/IMGP8824.jpg'),
  array('id' => '5149','post_title' => 'Lucifer & Coronation','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/IMGP9518-Version-21.jpg'),
  array('id' => '5469','post_title' => 'Tulipa \'Peach Blossom\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/40791-Tulipa-Peach-Blossom1.jpg'),
  array('id' => '5518','post_title' => 'Tulipa \'Willem van Oranje\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/203096-Springflowering-Bulbs.jpg'),
  array('id' => '5525','post_title' => 'Waterlily Tulips (Kaufmanniana Tulips)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207054-Tulipa-Hearts-Delight.jpg'),
  array('id' => '5579','post_title' => 'Squill \'Tubergeniana\' (Scilla Mischtschenkoana)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/45172-Scilla-mischtschenkoana-1.jpg'),
  array('id' => '5603','post_title' => 'Siberian Squill (Scilla Siberica)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44597-Scilla-siberica-Spring-Beauty.jpg'),
  array('id' => '5671','post_title' => 'Pearl of Spain \'Album\' (Muscari Botryoides)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/botryoides.xml_.jpg'),
  array('id' => '5689','post_title' => 'Grape Hyacinth (Muscari Azureum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44144-Muscari-azureum.jpg'),
  array('id' => '5703','post_title' => 'Grecian Windflower (Anemone Blanda)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44746-Anemone-blanda-Blue-Shades.jpg'),
  array('id' => '5744','post_title' => 'Darwin Hybrid Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35515-Tulipa-Daydream.jpg'),
  array('id' => '5829','post_title' => 'Double Late Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35151-Tulipa-Finola-®.jpg'),
  array('id' => '24382','post_title' => 'Tulipa \'Wirosa\' - OK','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/13353.jpg'),
  array('id' => '5858','post_title' => 'Fosteriana Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/1104-Tulipa-Juan.jpg'),
  array('id' => '5915','post_title' => 'Fringed Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35072-Tulipa-Fringed-Elegance.jpg'),
  array('id' => '5940','post_title' => 'Greigii Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35744-Tulipa-Pinocchio.jpg'),
  array('id' => '5990','post_title' => 'Lily-Flowered Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207156-Tulipa-Ballade.jpg'),
  array('id' => '6017','post_title' => 'Parrot Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/25834-Tulipa-Estella-Rijnveld.jpg'),
  array('id' => '6054','post_title' => 'Single Late Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/23069-Tulipa-Dreamland-®.jpg'),
  array('id' => '6184','post_title' => 'Viridiflora Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/203500-Tulipa-Esperanto.jpg'),
  array('id' => '6202','post_title' => 'Single Early Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/33561-Tulipa-White-Marvel.jpg'),
  array('id' => '6225','post_title' => 'Double Early Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/201720-Tulipa-Murillo.jpg'),
  array('id' => '6249','post_title' => 'Triumph Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/203262-Tulipa-Leen-van-der-Mark.jpg'),
  array('id' => '6273','post_title' => 'Rembrandt Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35402-Tulipa-Sorbet-®.jpg'),
  array('id' => '6287','post_title' => 'Other Botanical Tulips','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35125-Tulipa-humilis-Violacea.jpg'),
  array('id' => '6391','post_title' => 'A Red & Purple Carpet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44796.jpg'),
  array('id' => '6399','post_title' => 'Crocus ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/204919-Crocus-vernus-Remembrance1.jpg'),
  array('id' => '6455','post_title' => 'Crocus Luteus (Crocus Flavus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/Crocus-flavus.jpg'),
  array('id' => '6474','post_title' => 'Crocus Sieberi','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44568-Crocus-sieberi-ssp-sublimis-Tricolor.jpg'),
  array('id' => '6499','post_title' => 'Botanical Crocus (Crocus Tommasinianus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44131-Crocus-tommasinianus-Whitewell-Purple.jpg'),
  array('id' => '6512','post_title' => 'Dutch Crocus (Crocus Vernus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/45031-Crocus-vernus-Pickwick.jpg'),
  array('id' => '6542','post_title' => 'Lasagna Planting Method','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/17693-Springflowering-Bulbs.jpg'),
  array('id' => '6589','post_title' => 'Spring Is Back!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207165.jpg'),
  array('id' => '6596','post_title' => 'Spring Meadow','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/90187-Springflowering-Bulbs.jpg'),
  array('id' => '6631','post_title' => 'Daffodil & Jonquil (Narcissus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/203256-Narcissus-Carlton.jpg'),
  array('id' => '6643','post_title' => 'Daffodils, Narcissus Bulbocodium Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3417-Narcissus-Bulbocodium.jpg'),
  array('id' => '6645','post_title' => 'Daffodils, Narcissus Cyclamineus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/206440-Narcissus-Peeping-Tom.jpg'),
  array('id' => '6647','post_title' => 'Daffodils, Double Narcissus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3892-Narcissus-Sir-Winston-Churchill.jpg'),
  array('id' => '6656','post_title' => 'Daffodils, Small Cupped Narcissus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/30130-Narcissus-White-Lady.jpg'),
  array('id' => '6658','post_title' => 'Daffodils, Split-Corona Narcissus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/201285-Narcissus-Wild-Carnaval-1.jpg'),
  array('id' => '6660','post_title' => 'Daffodils, Triandrus Narcissus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/90448-Narcissus-Thalia.jpg'),
  array('id' => '6662','post_title' => 'Daffodils, Tazetta Narcissus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/201381-Narcissus-Avalanche.jpg'),
  array('id' => '6664','post_title' => 'Daffodils, Trumpet Narcissus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3900-Narcissus-Dutch-Master.jpg'),
  array('id' => '6652','post_title' => 'Daffodils, Narcissus Lobularis Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3293-Narcissus-Lobularis-2.jpg'),
  array('id' => '6650','post_title' => 'Daffodils, Narcissus Jonquilla Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/206436-Narcissus-Pueblo1.jpg'),
  array('id' => '6654','post_title' => 'Daffodils, Narcissus Poeticus Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3914-Narcissus-Actaea.jpg'),
  array('id' => '6869','post_title' => 'Daffodils, Large-Cupped Narcissus group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/30124-Narcissus-Birma.jpg'),
  array('id' => '6923','post_title' => 'Glory Of The Snow (Chionodoxa)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/44635-Chionodoxa-forbesii2.jpg'),
  array('id' => '6971','post_title' => 'Star of Bethlehem (Ornithogalum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/ornithogalum.xml_.jpg'),
  array('id' => '7499','post_title' => 'Heart\'s Delight','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35423-Tulipa-Hearts-Delight.jpg'),
  array('id' => '7069','post_title' => 'Snowflake (Leucojum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/202152-Leucojum-aestivum-Gravetye-Giant.jpg'),
  array('id' => '7084','post_title' => 'Summer Snowflake (Leucojum Aestivum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/206486-Leucojum-aestivum-Gravetye-Giant.jpg'),
  array('id' => '7095','post_title' => 'Spring Snowflake (Leucojum Vernum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/45133-Leucojum-vernum.jpg'),
  array('id' => '7114','post_title' => 'Dancing Queens','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/90012.jpg'),
  array('id' => '7141','post_title' => 'Pink River','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/10926.jpg'),
  array('id' => '7161','post_title' => 'Blossom Delight ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/10823.jpg'),
  array('id' => '7175','post_title' => 'Kiss & Diamond','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/90050.jpg'),
  array('id' => '7195','post_title' => 'Elegance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/90186.jpg'),
  array('id' => '7310','post_title' => 'A Magic Carpet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/206875-Anemone-blanda-White-Splendour.jpg'),
  array('id' => '7347','post_title' => 'A Vibrant Spring Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/10283-Tulipa-Ancilla.jpg'),
  array('id' => '7357','post_title' => 'Fireworks','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/203479.jpg'),
  array('id' => '7363','post_title' => 'Blushing Bride','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/207082-Tulipa.jpg'),
  array('id' => '7376','post_title' => 'A Sparkling Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/202948.jpg'),
  array('id' => '7393','post_title' => 'A Classic Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/207238.jpg'),
  array('id' => '7403','post_title' => 'Carnaval','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35464-Tulipa-Carnaval-de-Nice.jpg'),
  array('id' => '7411','post_title' => 'Romance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90347.jpg'),
  array('id' => '7421','post_title' => 'Dream Land','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90220.jpg'),
  array('id' => '7436','post_title' => 'A Romantic Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/203085.jpg'),
  array('id' => '7513','post_title' => 'Show Winner','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207012-Tulipa-Showwinner.jpg'),
  array('id' => '7520','post_title' => 'Stresa & Remembrance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35710.jpg'),
  array('id' => '7537','post_title' => 'Ancilla & Remembrance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/25883-Tulipa-Ancilla.jpg'),
  array('id' => '7542','post_title' => 'Heart\'s Delight & Pickwick','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35996-Tulipa-Hearts-Delight-1.jpg'),
  array('id' => '7550','post_title' => 'Princesses & Crocuses','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/36045.jpg'),
  array('id' => '7556','post_title' => 'A Wonderful Flower Carpet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/207047-Tulipa-Ancilla.jpg'),
  array('id' => '7566','post_title' => 'A Gold & Red Flower Carpet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35708.jpg'),
  array('id' => '7570','post_title' => 'Love Song & Grand Maitre','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35997-Tulipa-Love-Song.jpg'),
  array('id' => '7576','post_title' => 'Heart\'s Delight Over Gold','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/207052-Springflowering-Bulbs1.jpg'),
  array('id' => '7585','post_title' => 'Tres Chic Heart\'s Delight','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207057-Tulipa-Hearts-Delight.jpg'),
  array('id' => '7591','post_title' => 'Ballerinas','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35885.jpg'),
  array('id' => '7623','post_title' => 'A Royal Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/206945-Tulipa-Orange-Emperor.jpg'),
  array('id' => '7643','post_title' => 'Emperor & Purissima','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/203561.jpg'),
  array('id' => '7648','post_title' => 'A Romantic Setting','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90277.jpg'),
  array('id' => '7687','post_title' => 'Carnaval De Rio','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/202825.jpg'),
  array('id' => '7702','post_title' => 'Solstice & Gold','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/202718-Springflowering-Bulbs.jpg'),
  array('id' => '7720','post_title' => 'Purple Harmony','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90291.jpg'),
  array('id' => '7744','post_title' => 'Dreamboat Party','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90392.jpg'),
  array('id' => '7764','post_title' => 'Bleu Blanc Rouge','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/36044.jpg'),
  array('id' => '7773','post_title' => 'Sweet Lady River','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35683-Tulipa-Sweet-Lady.jpg'),
  array('id' => '7929','post_title' => 'Elegant Ladies','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207060-Tulipa-Elegant-Lady-1.jpg'),
  array('id' => '7938','post_title' => 'Barcelona & Holland Chic','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/10942-Tulipa-Holland-Chic-®.jpg'),
  array('id' => '7947','post_title' => 'Queen & Parrots','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/10682.jpg'),
  array('id' => '7958','post_title' => 'Bouquet of Gold','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/206994-Springflowering-Bulbs1.jpg'),
  array('id' => '7976','post_title' => 'A Festive Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90071.jpg'),
  array('id' => '7997','post_title' => 'Emperor & Attila','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90046.jpg'),
  array('id' => '8023','post_title' => 'Bluebell (Hyacinthoides)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/Hyacinthoides.jpg'),
  array('id' => '8029','post_title' => 'Spanish Bluebell (Hyacinthoides Hispanica)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/Hyacinthoides-hispanica.jpg'),
  array('id' => '8043','post_title' => 'English Bluebell, Hyacinthoides Non-Scripta','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/Hyacinthoides-non-scripta.jpg'),
  array('id' => '8056','post_title' => 'Angelique & Company','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/90311.jpg'),
  array('id' => '8114','post_title' => 'A Royal Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35691-Tulipa.jpg'),
  array('id' => '8136','post_title' => 'Menton & Company','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/203438.jpg'),
  array('id' => '8141','post_title' => 'Christmas Dream','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/30193.jpg'),
  array('id' => '8298','post_title' => 'Crown Imperial (Fritillaria Imperialis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/206629-Fritillaria-imperialis-Aurora.jpg'),
  array('id' => '8309','post_title' => 'Persia (Fritillaria Persica)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/44591-Fritillaria-persica.jpg'),
  array('id' => '8320','post_title' => 'Snake\'s Head Fritillary (Fritillaria Meleagris)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/44304-Fritillaria-meleagris.jpg'),
  array('id' => '8327','post_title' => 'Fritillaria','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/206893-Fritillaria-imperialis-Premier.jpg'),
  array('id' => '8337','post_title' => 'Just Beautiful!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/90281.jpg'),
  array('id' => '8352','post_title' => 'Pink Bouquet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/203498.jpg'),
  array('id' => '8359','post_title' => 'Pink Desire','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/23109.jpg'),
  array('id' => '9312','post_title' => 'Spring Celebration in Central Park! ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_88371.jpg'),
  array('id' => '9334','post_title' => 'Spring Colors at the Old Westbury Gardens','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_8956.jpg'),
  array('id' => '9465','post_title' => 'Pink & Purple Dreams','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_8919.jpg'),
  array('id' => '9477','post_title' => 'Stunning Apricot','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/Narcissus-Riot.jpg'),
  array('id' => '9491','post_title' => 'Big Smiles','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_89431.jpg'),
  array('id' => '9501','post_title' => 'A Dazzling Mix!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_89651.jpg'),
  array('id' => '9518','post_title' => 'Blushing Grace','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_8868-Version-2.jpg'),
  array('id' => '1140','post_title' => 'Plant Requirements Definitions','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/10/203280-Tulipa.jpg'),
  array('id' => '9590','post_title' => 'Plant Colorful Mid-Season Combos In Fall','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/35462-Tulipa-turkestanica.jpg'),
  array('id' => '9570','post_title' => 'Plant Colorful Early-Season Spring Combos this Fall','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/23468-Narcissus.jpg'),
  array('id' => '9592','post_title' => 'Plant Colorful Late Mid-Season Combos in Fall ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/10721-Tulipa-Mount-Tacoma.jpg'),
  array('id' => '9594','post_title' => 'Plant Colorful Early Late-Season Combos In Fall ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/25708-Tulipa-Ballerina.jpg'),
  array('id' => '9596','post_title' => 'A Pink And Purple Combo','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/10732.jpg'),
  array('id' => '9669','post_title' => 'Plant Colorful Late-Season Combos in Fall','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/35901-Tulipa-Spring-Green.jpg'),
  array('id' => '10956','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/foto7.jpg'),
  array('id' => '9840','post_title' => 'Simple & Beautiful','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/10158.jpg'),
  array('id' => '9875','post_title' => 'Romantic Blossoms in Brooklyn','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_9386.jpg'),
  array('id' => '9934','post_title' => 'Avignon ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/35465-Tulipa-Avignon-®.jpg'),
  array('id' => '9957','post_title' => 'Double Romance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/35151.jpg'),
  array('id' => '12510','post_title' => 'Tulipa \'Mount Tacoma\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/DSC_9144.jpg'),
  array('id' => '9990','post_title' => 'Symphony','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/DSC_9145_2.jpg'),
  array('id' => '10035','post_title' => 'An Artful Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/203213-Tulipa-Recreado.jpg'),
  array('id' => '13672','post_title' => 'A Charming Checkerboard Path - Schmechtig Landscapes','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Schmechtig-Landscapes.jpg'),
  array('id' => '10136','post_title' => 'Renewed Delight','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/DSC_9656.jpg'),
  array('id' => '10516','post_title' => 'Triumph','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/201304.jpg'),
  array('id' => '10530','post_title' => 'Marvels','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/203095.jpg'),
  array('id' => '10553','post_title' => 'A Famous Spring Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/203459.jpg'),
  array('id' => '10597','post_title' => 'Viva Dyanito! ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/203518-Springflowering-Bulbs1.jpg'),
  array('id' => '10645','post_title' => 'Quamash (Camassia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/Camassia.jpg'),
  array('id' => '10659','post_title' => 'Allium \'Purple Sensation\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/206866-Allium-aflatunense-Purple-Sensation-®.jpg'),
  array('id' => '10674','post_title' => 'Purple Sensation','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/203180-Allium-aflatunense-Purple-Sensation-®.jpg'),
  array('id' => '10683','post_title' => 'Tulipa Heart\'s Delight','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/35423-Tulipa-Hearts-Delight.jpg'),
  array('id' => '10691','post_title' => 'Tulipa Showwinner','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/35709-Tulipa-Showwinner.jpg'),
  array('id' => '10699','post_title' => 'Tulipa \'Orange Emperor\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/201735-Tulipa-Orange-Emperor.jpg'),
  array('id' => '10719','post_title' => 'Allium & Camassia','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/DSC_96281.jpg'),
  array('id' => '10738','post_title' => 'A Romantic Dutch Garden','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/foto4.jpg'),
  array('id' => '10747','post_title' => 'Purple Sensations','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/SNC14617-2.jpg'),
  array('id' => '10832','post_title' => 'Purple Devotion','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/SNC14595.jpg'),
  array('id' => '10839','post_title' => 'Wake Up!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/SNC14034.jpg'),
  array('id' => '10890','post_title' => 'Purple Delight','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/foto31.jpg'),
  array('id' => '11083','post_title' => 'Sweet Blossoms','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/05/foto7.jpg'),
  array('id' => '11145','post_title' => 'Impressionistic Dream','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/06/5_25b.jpg'),
  array('id' => '11207','post_title' => 'A Fabulous Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/06/5_27.jpg'),
  array('id' => '11222','post_title' => 'For A Naturalistic Look','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/06/6_18f.jpg'),
  array('id' => '11240','post_title' => 'A Stunning Mix ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/11510-Lilium-Horizon-®.jpg'),
  array('id' => '11256','post_title' => 'Feathers & Colors!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/06/6_1i.jpg'),
  array('id' => '11269','post_title' => 'A Beautiful Trio','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/06/6_3.jpg'),
  array('id' => '11271','post_title' => 'Temptation','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/06/6_25b.jpg'),
  array('id' => '11336','post_title' => 'Apricot Harmony','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/11287-Dahlia-Bishop-of-Llandaff.jpg'),
  array('id' => '11352','post_title' => 'A Pastel Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/DSC_3224-Version-2.jpg'),
  array('id' => '11502','post_title' => 'Rainbow','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/IMGP9499.jpg'),
  array('id' => '11824','post_title' => 'Oh Marilyn!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/207065-Tulipa-Red-Shine-®.jpg'),
  array('id' => '11834','post_title' => 'Wow!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/90258.jpg'),
  array('id' => '11840','post_title' => 'Spring Duo ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/25834-Tulipa-Estella-Rijnveld.jpg'),
  array('id' => '11854','post_title' => 'Spring Sensations','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/31117.jpg'),
  array('id' => '11868','post_title' => 'Tulipa \'Marilyn\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/207065-Tulipa-Red-Shine-®.jpg'),
  array('id' => '11873','post_title' => 'Tulipa \'Red Shine\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/31119-Tulipa-Red-Shine-®-1.jpg'),
  array('id' => '11875','post_title' => 'Magnificence','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/25808-Tulipa-Queen-of-Night.jpg'),
  array('id' => '12088','post_title' => 'Allium \'Globemaster\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Allium-macleanii-Globemaster-®.jpg'),
  array('id' => '12080','post_title' => 'Tulipa \'Arabian Mystery\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/35748-Tulipa-Arabian-Mystery.jpg'),
  array('id' => '12315','post_title' => 'Glorious Negrita','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/207008-Tulipa-Negrita.jpg'),
  array('id' => '12310','post_title' => 'Tulipa \'Negrita\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/35572-Tulipa-Negrita1.jpg'),
  array('id' => '12326','post_title' => 'Tulipa \'Queen Of Night\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/207206-Tulipa-Queen-of-Night.jpg'),
  array('id' => '12374','post_title' => 'Tulipa \'White Triumphator\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/25664-Tulipa-White-Triumphator.jpg'),
  array('id' => '12387','post_title' => 'Tulipa \'Shirley\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/35144-Tulipa-Shirley.jpg'),
  array('id' => '12397','post_title' => 'Tulipa \'Pink Impression\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/15484-Tulipa-Pink-Impression.jpg'),
  array('id' => '12402','post_title' => 'A Stunning Display','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/202817.jpg'),
  array('id' => '12414','post_title' => 'Tulipa \'Ballerina\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/25708-Tulipa-Ballerina.jpg'),
  array('id' => '12419','post_title' => 'A Fabulous Duo','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/20453-Tulipa-Mona-Lisa-®.jpg'),
  array('id' => '12428','post_title' => 'Happiness','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/90053.jpg'),
  array('id' => '12442','post_title' => 'AMAZING BULB IDEAS FOR FALL PLANTING','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/1730733.jpg'),
  array('id' => '12465','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Danks-Street-COS-Design1.jpg'),
  array('id' => '12491','post_title' => 'Tulipa \'Menton\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/DSC_9621.jpg'),
  array('id' => '12498','post_title' => 'Tulipa \'Angelique\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/25759-Tulipa-Angélique.jpg'),
  array('id' => '12516','post_title' => 'Tulipa \'Purissima\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/202768-Tulipa-Purissima1.jpg'),
  array('id' => '12586','post_title' => 'A Natural Path -  Lankford Associates Landscape Architects','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/1.jpg'),
  array('id' => '12648','post_title' => 'Tulipa \'Apricot Beauty\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/208271-Tulipa-Apricot-Beauty.jpg'),
  array('id' => '12655','post_title' => 'Tulipa \'Renown\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/35690-Tulipa.jpg'),
  array('id' => '12661','post_title' => 'Tulipa \'New Design\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/201602-Tulipa-New-Design.jpg'),
  array('id' => '12667','post_title' => 'Tulipa \'Yokohama\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/34362-Tulipa-Yokohama-®.jpg'),
  array('id' => '12673','post_title' => 'Tulipa \'Spring Green\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/04/35901-Tulipa-Spring-Green.jpg'),
  array('id' => '12803','post_title' => 'A European Style Courtyard - Thomas Kyle Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Courtyard-Thomas-Kyle.jpg'),
  array('id' => '12819','post_title' => 'Urban Creek - Envision Landscape Studio','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Urban-Creek-Envision-Landscape-Studio.jpg'),
  array('id' => '12830','post_title' => 'Secret Garden - Slater Associates','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Secret-Garden-2bis-Slater-Associates.jpg'),
  array('id' => '12846','post_title' => 'A Cosy Fire Pit Area - Wendy Resin','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Firepit-Area-Wendy-Resin-Interiors.jpg'),
  array('id' => '12859','post_title' => 'Playa La Vista - Pat Brodie Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Vista-la-Playa-2-Pat-Brodie.jpg'),
  array('id' => '12870','post_title' => 'Heaven In My Yard - 	Richard Lusk Landscape and Design ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Rear-yard-Richard-Lusk.jpg'),
  array('id' => '12881','post_title' => 'A Lovely Cottage Garden - Van De Voorde Elemental Design Group','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Cottage-garden-Van-de-Voorde1.jpg'),
  array('id' => '12884','post_title' => 'A Small French Courtyard - Isler Homes','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/French-Courtyard-Isler-homes.jpg'),
  array('id' => '12888','post_title' => 'A Small Asian Backyard - Goodman Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Small-spaces-Goodman-Landscape-Design.jpg'),
  array('id' => '12895','post_title' => 'A Fusion Courtyard - C.O.S. Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Danks-Street-COS-Design.jpg'),
  array('id' => '12902','post_title' => 'A Cozy Patio - Debora Carl Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Garden-Retreat-Debora-Carl.jpg'),
  array('id' => '12931','post_title' => 'A Charming Gravel Garden - Debora Carl landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Garden-Retreat-2-Debora-Carl.jpg'),
  array('id' => '12899','post_title' => '5 Tips To Maximise A Small Space','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/Garden-Retreat-2-Debora-Carl.jpg'),
  array('id' => '13096','post_title' => 'A Mediterranean Path - Gardens by Gabriel','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Mediterranean-Path-Gabriel.jpg'),
  array('id' => '13152','post_title' => 'Seacost Planting - Genevieve Schmidt Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Seacost-Planting-genevieve-Schmidt.jpg'),
  array('id' => '13172','post_title' => 'A Coastal Cottage garden - Van De Voorde Elemental Design Group ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Cottage-garden-2-Van-de-Voorde.jpg'),
  array('id' => '13185','post_title' => 'Tips To Add Drama To Your Walls','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/My-Sunny-Balcony.jpg'),
  array('id' => '13204','post_title' => 'Jazz Up your Walls - Vertical Gardening','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Bright-Green.jpg'),
  array('id' => '13228','post_title' => 'A Serene Courtyard - WA Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/WA-Design.jpg'),
  array('id' => '13263','post_title' => 'A successful Marriage - WA Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/WA-Design-2.jpg'),
  array('id' => '13280','post_title' => 'A delightful Scenery - Dig Your Garden','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Dig-Your-Garden.jpg'),
  array('id' => '13303','post_title' => 'Drama In My Garden! - Pat Brodie Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Pat-Broodie.jpg'),
  array('id' => '13351','post_title' => 'Sparkles - Carl Balton & Associates','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Carl-Balton.jpg'),
  array('id' => '13371','post_title' => 'A Welcoming Entrance Border - Designing Eden','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Designing-Eden.jpg'),
  array('id' => '13388','post_title' => 'Burst Of Colors - Pat Brodie Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Pat-Broodie2.jpg'),
  array('id' => '13429','post_title' => 'A Fantastic Hedge - Jean Marsh Design Inc','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Salvia-Fountain-grass-Jean-March1.jpg'),
  array('id' => '13440','post_title' => 'A Water Wise Path - Jean Marsh Design Inc','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Water-Wise-Design2-Jean-Marsh.jpg'),
  array('id' => '13465','post_title' => 'A Contemporary Provencal Courtyard - Suzman Design Associates ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Suzman-Design-Associates1.jpg'),
  array('id' => '13478','post_title' => 'Plant a River of Flowers - Van de Voorde Elemental Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Purple-River-Van-de-Voorde.jpg'),
  array('id' => '13498','post_title' => 'A Fabulous Yard - Debora Carl Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Debora-Carl-1.jpg'),
  array('id' => '13509','post_title' => 'A Fabulous Border - Debora Carl Landscape Design ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Debora-Carl-6.jpg'),
  array('id' => '13531','post_title' => 'A Welcoming Hedge - Denise Dering Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Denise-Dering-1.jpg'),
  array('id' => '13759','post_title' => 'Secret Garden Entry - Integration Design Studio','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Integration-Design-Studio1.jpg'),
  array('id' => '13768','post_title' => 'A Fun & Natural Path - Suzman Design Associates','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Suzman-Design-Associates2.jpg'),
  array('id' => '13773','post_title' => 'A Side Yard Beauty - RDM Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/RDM-Architecture.jpg'),
  array('id' => '13797','post_title' => 'A Mediterranean Path - Goodman Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/08/Goodman-Landscape2.jpg'),
  array('id' => '14891','post_title' => 'Surprise! - Liquidscapes ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/Liquidscapes.jpg'),
  array('id' => '14914','post_title' => 'Eye-Catching Retaining Walls - Liquidscapes ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/Liquidscapes2.jpg'),
  array('id' => '14917','post_title' => 'A Color Festival - Liquidscapes','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/11/Liquidscapes4.jpg'),
  array('id' => '17346','post_title' => 'Urban Retreat - C.O.S Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/COS51.jpg'),
  array('id' => '17340','post_title' => 'Let\'s Put Art On The Fence! - C.O.S Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/COS7.jpg'),
  array('id' => '17326','post_title' => 'Modern Elegance - C.O.S Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/COS6.jpg'),
  array('id' => '17304','post_title' => 'A Californian Retreat - Debora Carl Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Debora-Carl-10.jpg'),
  array('id' => '17354','post_title' => 'Garden Retreat - Fernhill Landscapes','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Fernhill-Landscapes.jpg'),
  array('id' => '17380','post_title' => 'Turn A Terrace into a French Courtyard - The Labyrinth Garden','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/The-Labyrinth.jpg'),
  array('id' => '17384','post_title' => 'A Romantic Terrace - Westover Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Westover-4.jpg'),
  array('id' => '17402','post_title' => 'A Serene Courtyard - Westover Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Westover-1.jpg'),
  array('id' => '17408','post_title' => 'A Low Maintenance Charming Courtyard - Studio H Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Studio-H1.jpg'),
  array('id' => '17425','post_title' => 'A Lovely Mediterranean Garden - Shades Of Green Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Shades-of-Green.jpg'),
  array('id' => '13252','post_title' => 'Lavender Main Types','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/lavender.jpg'),
  array('id' => '17509','post_title' => 'A Fabulous Pool - Studio H Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Studio-H2.jpg'),
  array('id' => '17523','post_title' => 'A Dramatic Entryway - Joel Loblaw','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Joel-Loblaw1.jpg'),
  array('id' => '17515','post_title' => 'A Fantastic Hedge - AHBL Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/AHBL.jpg'),
  array('id' => '17540','post_title' => 'A Bamboo Hedge - Habitat Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Habitat-Design2.jpg'),
  array('id' => '17551','post_title' => 'A Romantic Hedge - Westover Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Westover.jpg'),
  array('id' => '17555','post_title' => 'A Colorful Front Walk - AG-Trac Enterprises ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/AG-Trac.jpg'),
  array('id' => '17589','post_title' => 'Curb Appeal - Thomas Kyle Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Thomas-Kyle.jpg'),
  array('id' => '17603','post_title' => 'Splashes Of Colors For My Shady Garden - Carter Rohrer Co.','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Leslie-Rohrer.jpg'),
  array('id' => '17625','post_title' => 'A Dream Outdoor Space - AHBL Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/AHBL21.jpg'),
  array('id' => '17645','post_title' => 'An Inviting Home Entry - AHBL Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/AHBL3.jpg'),
  array('id' => '17651','post_title' => 'A Majestic Walkway - Liquidscapes','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Liquidscape6.jpg'),
  array('id' => '17691','post_title' => 'Pergola, Arbor, Trellis ? I am Confused!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Wysteria-pergola.jpg'),
  array('id' => '17705','post_title' => 'A Great Rose-Covered Entrance - Liquidscapes','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Liquiscape51.jpg'),
  array('id' => '17725','post_title' => 'A Fragrant Getaway - Katie Moss Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Katie-Moss1.jpg'),
  array('id' => '17739','post_title' => 'Tuscan Getaway - Bradanini','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Bradanini.jpg'),
  array('id' => '17742','post_title' => 'European Retreat In My Yard! - Carson Poetzl','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Carson-Poetzl.jpg'),
  array('id' => '17752','post_title' => 'Add Interest To Your Windows - Paul Moon Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Paul-Moon1.jpg'),
  array('id' => '17760','post_title' => 'A Relaxing Heaven - Cross River Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Cross-River-Design.jpg'),
  array('id' => '17770','post_title' => 'Modern rooftop pergola','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Begrand-Fast-Design.jpg'),
  array('id' => '17776','post_title' => 'Dreams Can Happen - Frank Holbrook ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Alex-Amend1.jpg'),
  array('id' => '17822','post_title' => 'Rooftop Retreat - MB Design & Build','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/MB-Design-Build.jpg'),
  array('id' => '17845','post_title' => 'An "All In One" Patio - Prideaux Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Prideaux3.jpg'),
  array('id' => '17873','post_title' => 'Add Drama And Character To Your Walkways - JSL Exteriors Landscape Design/Build	','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/JSL3.jpg'),
  array('id' => '18247','post_title' => 'A Fragrant Hedge - Chip-N-Dale\'s Custom Landscaping','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Chip-N-Dales.jpg'),
  array('id' => '18225','post_title' => 'Daisies, Daisies! Elliott Brundage Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Shasta-Daisy-image-copyrighted-2012.jpg'),
  array('id' => '18269','post_title' => 'A Perfect Entrance - Taylor Lombardo Architects','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Taylor-Lombardo.jpg'),
  array('id' => '20011','post_title' => 'A Fairytale Garden - Scotney Castle','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_1970.jpg'),
  array('id' => '19674','post_title' => 'Sissinghurst - A Garden For All Seasons','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/160022-12.jpg'),
  array('id' => '20034','post_title' => 'France Miniature, A Tour De France In A Day! ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_2546.jpg'),
  array('id' => '20111','post_title' => 'Once-Upon-A-Time Chateau De La Napoule','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_2851.jpg'),
  array('id' => '20149','post_title' => 'Hever Castle & Gardens: A Tudor Gem','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_2019.jpg'),
  array('id' => '20191','post_title' => 'A Famous Purple Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/160171-11.jpg'),
  array('id' => '20219','post_title' => 'A Radiant Cottage Garden In Late Spring ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/159450-11.jpg'),
  array('id' => '20256','post_title' => 'A Radiant Cottage Garden in Summer','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/160368-11.jpg'),
  array('id' => '20303','post_title' => 'A Cheerful Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1235741.jpg'),
  array('id' => '20351','post_title' => 'Ham House And Garden, A Unique Glimpse Of The Past','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1555592.jpg'),
  array('id' => '20407','post_title' => 'A Sunny Border','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_2922.jpg'),
  array('id' => '20480','post_title' => 'A Beautiful Pair','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_3727.jpg'),
  array('id' => '20491','post_title' => 'Convert A Dull Spot Into A Dream Place','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1604941.jpg'),
  array('id' => '20568','post_title' => 'Red Hot Poker (Kniphofia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/7786481.jpg'),
  array('id' => '20620','post_title' => 'Lily Of The Nile (Agapanthus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/Agapanthus1.jpg'),
  array('id' => '20645','post_title' => 'Montbretia (Crocosmia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1570341.jpg'),
  array('id' => '20736','post_title' => 'A Long-Lasting Border ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_3304.jpg'),
  array('id' => '20733','post_title' => 'Daylilies (Hemerocallis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/Hemerocallis-Autumn-Red.jpg'),
  array('id' => '20781','post_title' => 'Blue Anise Sage (Salvia Guaranitica)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/Salvia-Guaranitica-Black-Blue2.jpg'),
  array('id' => '21013','post_title' => 'A Striking Pair','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/12/11323-Agapanthus-Polar-Ice.jpg'),
  array('id' => '21027','post_title' => 'Subtile Elegance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/160396-11.jpg'),
  array('id' => '21057','post_title' => 'Attraction','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/11259-Crocosmia-crocosmiiflora-Walberton-Red.jpg'),
  array('id' => '21127','post_title' => 'Color Festival','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/IMGP9505.jpg'),
  array('id' => '23021','post_title' => 'Soft Harmony','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/17.jpg'),
  array('id' => '21191','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/DSC_66523.jpg'),
  array('id' => '21878','post_title' => 'Crocus Vernus \'Remembrance\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/44136-Crocus-vernus-Remembrance.jpg'),
  array('id' => '21902','post_title' => 'Lavender \'Hidcote\' ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/871471.jpg'),
  array('id' => '21945','post_title' => 'Hyssop (Agastache)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/Agastache_Blue_Boa_3b.jpg'),
  array('id' => '22057','post_title' => 'African Daisy (Arctotis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/raverspinksugar.jpg'),
  array('id' => '22086','post_title' => 'Narcissus \'Geranium\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/202566-Narcissus-Geranium.jpg'),
  array('id' => '22094','post_title' => 'Bleeding Heart (Dicentra Spectabilis)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/207332-Dicentra-spectabilis.jpg'),
  array('id' => '22123','post_title' => 'Feather Reed Grass (Calamagrostis x Acutiflora)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/Calamagrostis-Acutiflora.jpg'),
  array('id' => '22131','post_title' => 'Blue Fescue Grass (Festuca Glauca)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/festucaelijahblue.jpg'),
  array('id' => '22141','post_title' => 'An Elegant Front Garden - Debora Carl Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/Debora-Carl-8.jpg'),
  array('id' => '22175','post_title' => 'Catmint (Nepeta)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/9270373.jpg'),
  array('id' => '22286','post_title' => 'Mexican Feather Grass (Stipa Tenuissima)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/02/DSC_8407.jpg'),
  array('id' => '22304','post_title' => 'Lindheimer\'s Beeblossom (Gaura Lindheimeri)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/Stratosphere™-White-Gaura-lindheimeri.jpg'),
  array('id' => '22687','post_title' => 'A Fresh Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/206795-1.jpg'),
  array('id' => '22695','post_title' => 'Vibrant Spring Colors','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/207073-Tulipa-Hamilton.jpg'),
  array('id' => '22703','post_title' => 'A Wonderfully Fragrant Bouquet','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/23467-Tulipa-White-Dream1.jpg'),
  array('id' => '22719','post_title' => 'A Spectacular Spring Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/90086-1.jpg'),
  array('id' => '22843','post_title' => 'An Inviting Home Entry - AHBL Landscape Architecture','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/09/AHBL3.jpg'),
  array('id' => '21134','post_title' => 'A Striking Mix','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/610762.jpg'),
  array('id' => '21176','post_title' => 'A Super Trio ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/160372-12.jpg'),
  array('id' => '22016','post_title' => 'Columbine (Aquilegia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1513124.jpg'),
  array('id' => '20965','post_title' => 'Charming Achillea & Aster','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/778445.jpg'),
  array('id' => '20515','post_title' => 'Glowing Herbaceous Borders','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1569792.jpg'),
  array('id' => '20703','post_title' => 'Sneezeweed (Helenium)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1570021.jpg'),
  array('id' => '21983','post_title' => 'Wallflowers (Erysimum)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1553532.jpg'),
  array('id' => '21046','post_title' => 'A Hot Pair','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/1486231.jpg'),
  array('id' => '20325','post_title' => 'A Lovely Fragrant Path','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/650631.jpg'),
  array('id' => '221','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/02/7784452.jpg'),
  array('id' => '281','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2011/07/57170-1.jpg'),
  array('id' => '22985','post_title' => 'Fall Quatuor - await red dahlia name from Lisa Roper','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/10_5i.jpg'),
  array('id' => '21159','post_title' => 'A Distinctive Border ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/160379-11.jpg'),
  array('id' => '23037','post_title' => 'A Fall Long-Lasting Pair','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/DSC_6904.jpg'),
  array('id' => '23049','post_title' => 'A Superb Fall Trio ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/11/Kniphofia-Percys-Pride-and-Verbena-bonariensis-at-Longwood-Gardens.jpg'),
  array('id' => '23056','post_title' => 'A Charming Garden Entrance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/1599571.jpg'),
  array('id' => '23094','post_title' => 'Secret Garden Entrance - Andrew Renn Design ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/Andrew-Renn.jpg'),
  array('id' => '23072','post_title' => 'Great Fall Colors','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/8521712.jpg'),
  array('id' => '23122','post_title' => 'Enhance Your Exterior Walls - Andrew Renn Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/Andrew-Renn-2.jpg'),
  array('id' => '23158','post_title' => 'Striking Crocosmia & Aconitum','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/9716981.jpg'),
  array('id' => '23168','post_title' => 'Spring Cottage Scene','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/1765202.jpg'),
  array('id' => '23215','post_title' => 'Overbeck\'s, An Exotic Garden Dream','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/1569891.jpg'),
  array('id' => '23282','post_title' => 'Elegance - Louis Benech','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/Archives-©-Eric-Sander_MG_9516.jpg'),
  array('id' => '23249','post_title' => ' Breathtaking Winter Walk at Anglesey Abbey','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/12/936767.jpg'),
  array('id' => '23327','post_title' => 'A Stunning Perennial Garden - Matthew Cunningham Landscape Design','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/Matthew-Cunningham.jpg'),
  array('id' => '23349','post_title' => 'Spring Sparkles','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/31154.jpg'),
  array('id' => '23355','post_title' => 'Pastel Attraction','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/40792.jpg'),
  array('id' => '23365','post_title' => 'A Fantastic Spring Display!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/90099.jpg'),
  array('id' => '23529','post_title' => 'A Fabulous Spring Container Idea','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/209589.jpg'),
  array('id' => '23540','post_title' => 'Dwarf Iris (Iris Reticulata)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/207296.jpg'),
  array('id' => '23578','post_title' => 'Springtime bouquet!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/209236.jpg'),
  array('id' => '23586','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/15555.jpg'),
  array('id' => '23590','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/211858.jpg'),
  array('id' => '23593','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/209589-1.jpg'),
  array('id' => '12459','post_title' => '','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/07/65063.jpg'),
  array('id' => '23634','post_title' => 'Instant Spring In A Flower Pot!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/2093651.jpg'),
  array('id' => '23652','post_title' => 'Spring Colors!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/2053051.jpg'),
  array('id' => '23675','post_title' => 'Forgot To Plant Bulbs? Not A Problem!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/113154.jpg'),
  array('id' => '23706','post_title' => 'Sword-Lilies (Gladiolus)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/201838.jpg'),
  array('id' => '23781','post_title' => 'A Breathtaking Hedge','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/01/11416.jpg'),
  array('id' => '23799','post_title' => 'Tuberous Begonias','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/88194.jpg'),
  array('id' => '23836','post_title' => 'Spring In a Pot!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/10/spring_combo_121.jpg'),
  array('id' => '23929','post_title' => 'Snow White Inspiration','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/2091141.jpg'),
  array('id' => '23942','post_title' => 'Joy!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/209103.jpg'),
  array('id' => '23949','post_title' => 'Winter Butterflies','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/204430.jpg'),
  array('id' => '23901','post_title' => '12 Ideas To Bring Some Sunshine To Your Pots! ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/113028.jpg'),
  array('id' => '23980','post_title' => '3 Beauties In A Pot!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/1131291.jpg'),
  array('id' => '24000','post_title' => 'Spring Is In The Air!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/2091181.jpg'),
  array('id' => '23997','post_title' => 'Springtime!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/336182.jpg'),
  array('id' => '24081','post_title' => 'Creamy Elegance','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/40194.jpg'),
  array('id' => '23872','post_title' => 'Get a Jump on the Season','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/202533.jpg'),
  array('id' => '24150','post_title' => 'Calla Lilies (Zantedeschia)','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/210184.jpg'),
  array('id' => '24223','post_title' => 'Tulipa \'Yonina\' - Nrelate mixed up /  Best offers to add - Rest is ok','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/35058.jpg'),
  array('id' => '24323','post_title' => 'Narcissus Tahiti - Nrelate Issue / Best offers to add - Rest ok','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/02/3696-Narcissus-Tahiti-®.jpg'),
  array('id' => '24367','post_title' => 'Narcissus \'Tête à Tête\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/205290-Narcissus-Tête-à-Tête-1.jpg'),
  array('id' => '24397','post_title' => 'Narcissus \'Mount Hood\' /Price not the lowest/ Rest is ok','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2012/01/3332-Narcissus-Mount-Hood-®.jpg'),
  array('id' => '24414','post_title' => 'Tulipa \'Flaming Parrot\' / ok','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/34147-Tulipa-Flaming-Parrot.jpg'),
  array('id' => '24449','post_title' => 'Narcissus \'Erlicheer\' (or \'Early Cheer\') - Arrangement without a post - post to do - rest ok','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/13930-Narcissus-Erlicheer.jpg'),
  array('id' => '24351','post_title' => 'Cactus Dahlia: Summer Bulb Of The Year!','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77254.jpg'),
  array('id' => '24500','post_title' => 'Best Dahlias For Cutting','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/202122.jpg'),
  array('id' => '24544','post_title' => 'Best Dahlias For Containers & Low Borders','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/40230.jpg'),
  array('id' => '24624','post_title' => 'Giant Dinner Plate Dahlias','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77578.jpg'),
  array('id' => '24796','post_title' => 'Dahlia Sunshine','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77592.jpg'),
  array('id' => '24659','post_title' => 'Dahlias with “Black” Foliage','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/203090.jpg'),
  array('id' => '24711','post_title' => 'Dahlia \'Bishop of Llandaff\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/21702.jpg'),
  array('id' => '24748','post_title' => 'Dahlia \'David Howard\' ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/202505.jpg'),
  array('id' => '24757','post_title' => 'Dahlia \'Fascination\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/7442.jpg'),
  array('id' => '24765','post_title' => 'Dahlia \'Moonfire\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/23013.jpg'),
  array('id' => '24809','post_title' => 'Dahlia \'Café Au Lait\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/201892.jpg'),
  array('id' => '24819','post_title' => 'Dahlia \'Duet\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77213.jpg'),
  array('id' => '24841','post_title' => 'Dahlia \'Kelvin Floodlight\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77153.jpg'),
  array('id' => '24849','post_title' => 'Dahlia \'Mystery Day\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/210375.jpg'),
  array('id' => '24871','post_title' => 'Dahlia \'Karma Sangria\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77254.jpg'),
  array('id' => '24935','post_title' => 'Dahlia \'Arabian Night\' ','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/212846.jpg'),
  array('id' => '24962','post_title' => 'Dahlia \'Honka\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/212940.jpg'),
  array('id' => '24997','post_title' => 'Dahlia \'Melody Gipsy\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/775691.jpg'),
  array('id' => '25020','post_title' => 'Dahlia \'Melody Harmony"','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/21996-Dahlia-Melody-Harmony.jpg'),
  array('id' => '25035','post_title' => 'Dahlia \'Karma Fuchsiana\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/212872.jpg'),
  array('id' => '25050','post_title' => 'Dahlia \'Babylon\'','featured_image' => 'http://www.jardins-sans-secret.com/wp-content/uploads/2013/03/77185.jpg')
);

foreach ($wp_posts as $p)
{
	preg_match('/[^\/]+\.jpg$/is',$p["featured_image"],$match);
	$img = $match[0];
	mysql_query("UPDATE product SET main_picture='$img' WHERE name='".mysql_real_escape_string($p["post_title"])."'") or die (mysql_error());
}
?>
